---
image: gitpod/workspace-python-3.10:latest

tasks:
  - init: |
      pip install -r requirements.txt
      pip install pre-commit
      PIP_USER=no pre-commit install --install-hooks
vscode:
  extensions:
    - ms-python.python
    - vscode.markdown
